name: caftsiel

on:
  schedule:
    - cron: '0 0/2 * * *'
  workflow_dispatch: # 수동 실행 버튼

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24' # 👈 경고 해결: Node 버전을 24로 올립니다.
      
      - run: npm ci
      
      - name: Run Bot
        env:
          BSKY_USERNAME: ${{ secrets.BSKY_USERNAME_1 }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD_1 }}
          QUOTE_FILE: 'quotes_caftsiel.txt'
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true' # 👈 경고 해결: 최신 노드 강제 활성화
        run: npm start
